name: Home Key Go
version: "0.0.3"
slug: homekey_go
description: HomeKit virtual lock with Apple Home Key NFC authentication
url: https://sgit.k8s.astropenguin.net/penguin/homekey-go/
arch:
  - aarch64
  - amd64
startup: services
boot: auto
init: true
host_network: true
host_dbus: true
backup: cold
stage: experimental
image: ghcr.io/tgckpg/homekey-go
options:
  name: Go Home Key
  serial: GO-HOMEKEY-001
  port: 51826
  interface: ""
  finish: silver
  pin: ""
  ble_reader: ""
  ble_adapter: hci0
schema:
  name: str(1,)
  serial: str(1,)
  port: port
  interface: str
  finish: list(silver|black|gold|tan)
  pin: password
  ble_reader: str?
  ble_adapter: str?
